llm_model:
embeddings_model:
mode: 
text_chunk_size: 
text_chunk_overlap_size: 
confluence:
    username:
    api_key:
    url:
    confluence_spaces: 
datadog:
    api_host:
    api_key:
    app_key:
jira:
    url:
    username:
    api_key:
local_files:
    csv:
    txt:
