llm_model: "wizard-vicuna-13B.ggml.q5_1.bin"
embeddings_model: "sentence-transformers/all-MiniLM-L6-v2"
mode: "document_summarization" # One of "document_summarization", "multi_document_summarization", "summary_solution", "chatbot"
text_chunk_size: 1000
text_chunk_overlap_size: 20
confluence:
    username: 
    api_key: 
    url: 
    confluence_spaces: 
datadog:
    api_host: 
    api_key: 
    app_key: 
jira:
    url: 
    username:
    api_key:
local_files:
    csv: "data/"
    txt: "data/"
